**Hill and Valley Prediction Using Logistics Regression**

**Objective**

To develop an Machine Learning Model to predict Hill and Valley using Logistic Regression method that can accurately classify geographical locations as either hills or valleys based on a set of input features.

**Data Source**

Each record represents 100 points on a 2D graph .
when plotted in order as the y coordinate,the points will create either a Hill . See the original source for some examples of these graphs .

1-100 : Labeled "V##" . Floating point values ,the x - values .

101 : Labeled "class". binary (0,1) representing (valley,hill)

**Import Library**

In [ ]:
import pandas as pd
import numpy as np

**Import CSV as Dataframe**

use URL of File Directory

In [ ]:
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Hill%20Valley%20Dataset.csv')

**Get the First Five rows of Dataframe**

In [ ]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0     39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1      1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2  68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3  44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4      5.70      5.40      5.28      5.38      5.27      5.61      6.00   

         V8        V9       V10  ...       V92       V93       V94       V95  \
0     39.53     38.81     38.79  ...     36.62     36.92     38.80     38.52   
1      1.70      1.75      1.78  ...      1.80      1.79      1.77      1.74   
2  73268.61  74465.84  72503.37  ...  73438.88  71053.35  71112.62  74916.48   
3  37668.32  40980.89  38466.15  ...  42625.67  40684.20  46960.73  44546.80   
4      5.38      5.34      5.87  ...      5.17      5.67      5.60      5.94   

        V96       V97       V98       V99      V100  Class  
0     38.07     36.73     39.46     37.50     39.10      0  
1      1.74      1.80      1.78      1.75      1.69      1  
2  72571.58  66348.97  71063.72  67404.27  74920.24      1  
3  45410.53  47139.44  43095.68  40888.34  39615.19      0  
4      5.73      5.22      5.30      5.73      5.91      0  

[5 rows x 101 columns]

**Get information Of Dataframe**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Columns: 101 entries, V1 to Class
dtypes: float64(100), int64(1)
memory usage: 956.5 KB


**Get the Summary Statistics**

In [ ]:
df.describe()

V1             V2             V3             V4  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8169.091881    8144.306262    8192.653738    8176.868738   
std     17974.950461   17881.049734   18087.938901   17991.903982   
min         0.920000       0.900000       0.850000       0.890000   
25%        19.602500      19.595000      18.925000      19.277500   
50%       301.425000     295.205000     297.260000     299.720000   
75%      5358.795000    5417.847500    5393.367500    5388.482500   
max    117807.870000  108896.480000  119031.350000  110212.590000   

                  V5             V6             V7             V8  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8128.297211    8173.030008    8188.582748    8183.641543   
std     17846.757963   17927.114105   18029.562695   18048.582159   
min         0.880000       0.860000       0.870000       0.650000   
25%        19.210000      19.582500      18.690000      19.062500   
50%       295.115000     294.380000     295.935000     290.850000   
75%      5321.987500    5328.040000    5443.977500    5283.655000   
max    113000.470000  116848.390000  115609.240000  118522.320000   

                  V9            V10  ...            V92            V93  \
count    1212.000000    1212.000000  ...    1212.000000    1212.000000   
mean     8154.670066    8120.767574  ...    8120.056815    8125.917409   
std     17982.390713   17900.798206  ...   17773.190621   17758.182403   
min         0.650000       0.620000  ...       0.870000       0.900000   
25%        19.532500      19.285000  ...      19.197500      18.895000   
50%       294.565000     295.160000  ...     297.845000     295.420000   
75%      5378.180000    5319.097500  ...    5355.355000    5386.037500   
max    112895.900000  117798.300000  ...  113858.680000  112948.830000   

                 V94            V95            V96            V97  \
count    1212.000000    1212.000000    1212.000000    1212.000000   
mean     8158.793812    8140.885421    8213.480611    8185.594002   
std     17919.510371   17817.945646   18016.445265   17956.084223   
min         0.870000       0.880000       0.890000       0.890000   
25%        19.237500      19.385000      19.027500      19.135000   
50%       299.155000     293.355000     301.370000     296.960000   
75%      5286.385000    5345.797500    5300.890000    5361.047500   
max    112409.570000  112933.730000  112037.220000  115110.420000   

                 V98            V99           V100        Class  
count    1212.000000    1212.000000    1212.000000  1212.000000  
mean     8140.195355    8192.960891    8156.197376     0.500000  
std     17768.356106   18064.781479   17829.310973     0.500206  
min         0.860000       0.910000       0.890000     0.000000  
25%        19.205000      18.812500      19.145000     0.000000  
50%       300.925000     299.200000     302.275000     0.500000  
75%      5390.850000    5288.712500    5357.847500     1.000000  
max    116431.960000  113291.960000  114533.760000     1.000000  

[8 rows x 101 columns]

**Get Shape of Dataframe**

In [ ]:
df.shape

(1212, 101)

**Get Columns Names**

In [ ]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       ...
       'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100',
       'Class'],
      dtype='object', length=101)

All Columns name not printed

In [ ]:
print(df.columns.tolist())

['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'Class']


**Define y and x

In [ ]:
y = df['Class']


In [ ]:
y.shape

(1212,)

In [ ]:
y

0       0
1       1
2       1
3       0
4       0
       ..
1207    1
1208    0
1209    1
1210    1
1211    0
Name: Class, Length: 1212, dtype: int64

In [ ]:
x = df[['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100']]

or use.drop function to define X

In [ ]:
x = df.drop('Class',axis=1)

In [ ]:
x.shape

(1212, 100)

In [ ]:
x

V1        V2        V3        V4        V5        V6        V7  \
0        39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1         1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2     68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3     44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4         5.70      5.40      5.28      5.38      5.27      5.61      6.00   
...        ...       ...       ...       ...       ...       ...       ...   
1207     13.00     12.87     13.27     13.04     13.19     12.53     14.31   
1208     48.66     50.11     48.55     50.43     50.09     49.67     48.95   
1209  10160.65   9048.63   8994.94   9514.39   9814.74  10195.24  10031.47   
1210     34.81     35.07     34.98     32.37     34.16     34.03     33.31   
1211   8489.43   7672.98   9132.14   7985.73   8226.85   8554.28   8838.87   

            V8        V9       V10  ...       V91       V92       V93  \
0        39.53     38.81     38.79  ...     37.57     36.62     36.92   
1         1.70      1.75      1.78  ...      1.71      1.80      1.79   
2     73268.61  74465.84  72503.37  ...  69384.71  73438.88  71053.35   
3     37668.32  40980.89  38466.15  ...  47653.60  42625.67  40684.20   
4         5.38      5.34      5.87  ...      5.52      5.17      5.67   
...        ...       ...       ...  ...       ...       ...       ...   
1207     13.33     13.63     14.55  ...     12.89     12.48     12.15   
1208     48.65     48.63     48.61  ...     47.45     46.93     49.61   
1209  10202.28   9152.99   9591.75  ...  10413.41   9068.11   9191.80   
1210     32.48     35.63     32.48  ...     33.18     32.76     35.03   
1211   8967.24   8635.14   8544.37  ...   7747.70   8609.73   9209.48   

           V94       V95       V96       V97       V98       V99      V100  
0        38.80     38.52     38.07     36.73     39.46     37.50     39.10  
1         1.77      1.74      1.74      1.80      1.78      1.75      1.69  
2     71112.62  74916.48  72571.58  66348.97  71063.72  67404.27  74920.24  
3     46960.73  44546.80  45410.53  47139.44  43095.68  40888.34  39615.19  
4         5.60      5.94      5.73      5.22      5.30      5.73      5.91  
...        ...       ...       ...       ...       ...       ...       ...  
1207     13.15     12.35     13.58     13.86     12.88     13.87     13.51  
1208     47.16     48.17     47.94     49.81     49.89     47.43     47.77  
1209   9275.04   9848.18   9074.17   9601.74  10366.24   8997.60   9305.77  
1210     32.89     31.91     33.85     35.28     32.49     32.83     34.82  
1211   8496.33   8724.01   8219.99   8550.86   8679.43   8389.31   8712.80  

[1212 rows x 100 columns]

**Get Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=2529)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((909, 100), (303, 100), (909,), (303,))

**Get Model Train (Modeling)**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

**Get Model Prediction**

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
y_pred.shape

(303,)

In [ ]:
y_pred

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,

**Get Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[143   6]
 [  4 150]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97       149
           1       0.96      0.97      0.97       154

    accuracy                           0.97       303
   macro avg       0.97      0.97      0.97       303
weighted avg       0.97      0.97      0.97       303



**Get Future Prediction**

In [ ]:
x_new = df.sample(1)

In [ ]:
x_new

V1     V2     V3     V4     V5     V6     V7     V8     V9    V10  \
596  45.67  48.06  40.67  43.52  44.53  39.72  44.67  46.12  39.26  43.49   

     ...    V92    V93    V94    V95    V96    V97    V98    V99   V100  Class  
596  ...  44.13  48.51  47.97  42.31  45.03  45.04  46.15  45.85  42.79      0  

[1 rows x 101 columns]

In [ ]:
x_new.shape

(1, 101)

In [ ]:
x_new = x_new.drop('Class',axis=1)

In [ ]:
x_new

V1     V2     V3     V4     V5     V6     V7     V8     V9    V10  \
596  45.67  48.06  40.67  43.52  44.53  39.72  44.67  46.12  39.26  43.49   

     ...    V91    V92    V93    V94    V95    V96    V97    V98    V99   V100  
596  ...  43.55  44.13  48.51  47.97  42.31  45.03  45.04  46.15  45.85  42.79  

[1 rows x 100 columns]

In [ ]:
x_new.shape

(1, 100)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_new = ss.fit_transform(x_new)


In [ ]:
y_pred_new = lr.predict(x_new)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
y_pred_new

array([0])

In [ ]:
lr.predict_proba(x_new)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[0.50002892, 0.49997108]])